services:
  cap-web:
    container_name: cap-web
    image: ghcr.io/capsoftware/cap-web:latest
    restart: unless-stopped
    depends_on:
      - minio
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_PASSWORD}@mysql.zachtaiji.com:3307/planetscale
      - WEB_URL=https://cap.zachtaiji.com
      - NEXTAUTH_URL=https://cap.zachtaiji.com
      - DATABASE_ENCRYPTION_KEY=${DATABASE_ENCRYPTION_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      # CHANGE THESE TO MATCH YOUR MINIO or S3 STORAGE SETUP
      - CAP_AWS_ACCESS_KEY=${MINIO_ROOT_USER}
      - CAP_AWS_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - CAP_AWS_BUCKET=capso
      - CAP_AWS_REGION=us-west-1
      - S3_PUBLIC_ENDPOINT=minio:9000
      - S3_INTERNAL_ENDPOINT=minio:9000
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_DOMAIN=notifications.zachtaiji.com

    labels:
      - traefik.enable=true
      - traefik.http.routers.cap.entrypoints=web,websecure
      - traefik.http.routers.cap.rule=Host(`cap.zachtaiji.com`)
      - traefik.http.routers.cap.tls.certresolver=myresolver
      - traefik.http.routers.cap.middlewares=https_redirect@docker,non_www@docker
      - traefik.docker.network=reverse-proxynet
      - traefik.http.services.cap.loadbalancer.server.port=3000
    networks:
      - reverse-proxynet
      - cap-web

  # Local S3 Strorage
  minio:
    container_name: minio
    image: "minio/minio:latest"
    restart: unless-stopped
    command: server /data --console-address ":9001"
    expose:
      - "9000:9000"
    ports:
      - "9001:9001"
    environment:
      - MINIO_API_PORT_NUMBER=9000
      - MINIO_CONSOLE_PORT_NUMBER=9001
      # CHANGE THESE TO YOUR OWN VALUES
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      #- MINIO_SERVER_URL=localhost:9000
      #- MINIO_BROWSER_REDIRECT_URL=localhost:9001
    volumes:
      - ./minio-data:/data
      - ./minio-certs:/certs
    networks: [cap-web]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true
  cap-web:
    name: cap-web