services:
  postgres:
    container_name: postgres
    image: postgres:15.4
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.postgres.entrypoints=postgres
      - traefik.tcp.routers.postgres.tls=true
      - traefik.tcp.routers.postgres.rule=HostSNI(`postgres.zachtaiji.com`)
      - traefik.tcp.services.postgres.loadbalancer.server.port=5432
      - traefik.docker.network=reverse-proxynet
      #- traefik.tcp.routers.postgres.service=postgres-service
    networks: [reverse-proxynet]
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    volumes:
      - ./auth:/auth:ro
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.rule=Host(`adminer.zachtaiji.com`)
      - traefik.http.routers.adminer.entrypoints=websecure
      - traefik.http.routers.adminer.tls.certresolver=myresolver
      - traefik.http.services.adminer.loadbalancer.server.port=8080
      - traefik.http.routers.adminer.middlewares=adminer-basicauth
      - traefik.http.middlewares.adminer-basicauth.basicauth.usersfile=auth/.htpasswd     
      #- traefik.docker.network=reverse-proxynet
    networks: [reverse-proxynet]
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true